### ISSUE TITLE
Random freeze

### ISSUE THREAD

**Issue by gwilherm** [gwilherm/teeworlds-infection#17]
backtrace:
```
#0  0x00007f54e473c3f7 in random_r () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f54e473c55b in srandom_r () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f54e473c1b1 in srandom () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x000000000042f639 in IGameController::GenerateSetOfNumbers() ()
#4  0x000000000042f782 in IGameController::PickZombie() ()
#5  0x0000000000430ef7 in IGameController::Tick() ()
#6  0x00000000004472da in CGameContext::OnTick() ()
#7  0x000000000042567d in CServer::Run() ()
#8  0x0000000000408782 in main ()
```

**Comment by gwilherm** [comment]
Needed debug
